### ISSUE TITLE
Extra empty data tables

### ISSUE THREAD

**Issue by KarlaRosas** [Jlebours/WikipediaExtractor_Python#1]
For the first analysis we find 5 tables in  URL= https://en.wikipedia.org/wiki/Comparison_(grammar) 
Problems Table 1 and  Table 5.   Structure of the website
Table 1. 
![T1](https://user-images.githubusercontent.com/72513172/97322363-01c4a380-1870-11eb-834f-99ae576b36fa.JPG)

Table 2.
![Table2](https://user-images.githubusercontent.com/72513172/97322428-13a64680-1870-11eb-8a59-595be43a0a94.png)

Table 3.
![Table3](https://user-images.githubusercontent.com/72513172/97322468-1ef97200-1870-11eb-8c75-5e1da368e7a6.png)

Table 4.
![Tabla4](https://user-images.githubusercontent.com/72513172/97322497-26b91680-1870-11eb-924b-426df4e26f24.png)

Table 5.
![Tabla5](https://user-images.githubusercontent.com/72513172/97322517-2c166100-1870-11eb-8c3d-df3b34282a7d.png)

**Comment by Jlebours** [comment]
We must do precised selection to only tables that interest us, for exemple we can see, on this page, tables have the class="wikitable", so i precised the class in the selection : 
![image](https://user-images.githubusercontent.com/70755177/98105736-a52d3e00-1e98-11eb-83bc-e0524a4a0f87.png)
Now for this page we have the 2 tables that we want : 
![image](https://user-images.githubusercontent.com/70755177/98105572-7adb8080-1e98-11eb-9eb1-acf7ddbe2b4a.png)
![image](https://user-images.githubusercontent.com/70755177/98105588-8038cb00-1e98-11eb-9212-e349bf79ec2b.png)
![image](https://user-images.githubusercontent.com/70755177/98105617-875fd900-1e98-11eb-8e20-764738b5e382.png)
![image](https://user-images.githubusercontent.com/70755177/98105643-8d55ba00-1e98-11eb-940b-9358fd379ce1.png)
